services:
  orders-db:
    image: postgres:16.2
    container_name: orders-db
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
      POSTGRES_DB: ordersdb
